# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 4.1"
gem "sinatra-activerecord", "~> 2.0"
gem "sqlite3", "~> 2.6"
gem "rack-cors", "~> 2.0"
gem "puma", "~> 6.6"
gem "rake", "~> 13.0"

group :development do
  gem "rubocop", "~> 1.75"
end

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.2"
end
